"""
Sample Generated Playwright Tests - Phase 2 Output

This file contains examples of tests generated by the Phase 2 pipeline.
These are actual outputs from PlaywrightTestGenerator.generate_test_code()
"""

# ============================================================================
# EXAMPLE 1: Product Browsing Flow
# ============================================================================

GENERATED_TEST_PRODUCT_BROWSE = """
import { test, expect } from '@playwright/test';

test.describe('Browse Products', () => {
  test.beforeEach(async ({ page }) => {
    // Mock external API calls
    await page.route('**/api/products', async route => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          items: [
            { id: 1, name: "Product 1", price: 99.99 },
            { id: 2, name: "Product 2", price: 149.99 }
          ]
        })
      });
    });
  });

  test('User browses product catalog', async ({ page }) => {
    // Navigate to products page
    await page.goto('/products');
    
    // Wait for page load
    await page.waitForLoadState('networkidle');
    await page.waitForSelector('[data-testid="products-page"]');
    
    // Verify product list is displayed
    const productCards = page.locator('[data-testid="product-item"]');
    await expect(productCards.first()).toBeVisible();
    
    // Verify product information
    await expect(page.locator('.product-price').first()).toContainText('$');
    
    // Test interaction: add to cart
    const addButton = page.locator('[data-testid="add-to-cart-btn"]').first();
    await addButton.click();
    
    // Verify action
    await expect(page).not.toHaveTitle('Error');
  });

  test('User filters products by price', async ({ page }) => {
    await page.goto('/products');
    await page.waitForLoadState('networkidle');
    
    // Apply filter
    await page.click('[data-testid="filter-price"]');
    await page.selectOption('[data-testid="price-range"]', 'under-100');
    
    // Verify filtered results
    const items = page.locator('[data-testid="product-item"]');
    const count = await items.count();
    expect(count).toBeGreaterThan(0);
  });
});
"""

# ============================================================================
# EXAMPLE 2: User Authentication Flow
# ============================================================================

GENERATED_TEST_AUTH = """
import { test, expect } from '@playwright/test';

test.describe('User Login', () => {
  test.beforeEach(async ({ page }) => {
    // Mock login endpoint
    await page.route('**/api/auth/login', async route => {
      if (route.request().method() === 'POST') {
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            token: 'jwt_token_12345',
            user: { id: 1, email: 'user@test.com', name: 'Test User' }
          })
        });
      }
    });
  });

  test('User successfully logs in', async ({ page }) => {
    // Navigate to login page
    await page.goto('/login');
    
    // Fill login form
    await page.fill('[data-testid="email-input"]', 'user@test.com');
    await page.fill('[data-testid="password-input"]', 'password123');
    
    // Submit form
    await page.click('[data-testid="login-btn"]');
    
    // Wait for navigation to dashboard
    await page.waitForURL('**/dashboard');
    
    // Verify user is logged in
    await expect(page.locator('[data-testid="user-menu"]')).toContainText('Test User');
  });

  test('User sees error on invalid credentials', async ({ page }) => {
    // Setup mock for failed login
    await page.route('**/api/auth/login', route => {
      route.fulfill({ status: 401, body: JSON.stringify({ error: 'Invalid credentials' }) });
    });

    await page.goto('/login');
    await page.fill('[data-testid="email-input"]', 'wrong@test.com');
    await page.fill('[data-testid="password-input"]', 'wrong');
    await page.click('[data-testid="login-btn"]');
    
    // Error message appears
    await expect(page.locator('[data-testid="error-message"]')).toContainText('Invalid');
  });
});
"""

# ============================================================================
# EXAMPLE 3: Checkout Flow (Multi-Step)
# ============================================================================

GENERATED_TEST_CHECKOUT = """
import { test, expect } from '@playwright/test';

test.describe('Complete Checkout', () => {
  test.beforeEach(async ({ page }) => {
    // Mock cart endpoint
    await page.route('**/api/cart', async route => {
      await route.fulfill({
        status: 200,
        body: JSON.stringify({
          items: [{ id: 1, title: 'Product', price: 99.99, qty: 1 }],
          total: 99.99
        })
      });
    });

    // Mock checkout endpoint
    await page.route('**/api/checkout', async route => {
      if (route.request().method() === 'POST') {
        await route.fulfill({
          status: 200,
          body: JSON.stringify({
            orderId: 'ORDER-12345',
            status: 'confirmed'
          })
        });
      }
    });
  });

  test('User completes purchase flow', async ({ page }) => {
    // Start from cart page
    await page.goto('/cart');
    await page.waitForSelector('[data-testid="cart-items"]');
    
    // Proceed to checkout
    await page.click('[data-testid="checkout-btn"]');
    
    // Step 1: Shipping
    await page.waitForSelector('[data-testid="shipping-form"]');
    await page.fill('[data-testid="address-input"]', '123 Main St');
    await page.fill('[data-testid="city-input"]', 'New York');
    await page.selectOption('[data-testid="state-select"]', 'NY');
    await page.click('[data-testid="continue-payment"]');
    
    // Step 2: Payment
    await page.waitForSelector('[data-testid="payment-form"]');
    await page.fill('[data-testid="card-number"]', '4111111111111111');
    await page.fill('[data-testid="expiry"]', '12/25');
    await page.fill('[data-testid="cvv"]', '123');
    
    // Complete purchase
    await page.click('[data-testid="place-order-btn"]');
    
    // Verify success
    await page.waitForURL('**/confirmation**');
    await expect(page.locator('[data-testid="order-number"]')).toContainText('ORDER-');
  });
});
"""

# ============================================================================
# EXAMPLE 4: Generated Fixtures File
# ============================================================================

GENERATED_FIXTURES = """
import { test as base, expect } from '@playwright/test';

export const test = base.extend({
  mockApis: async ({ page }, use) => {
    const interceptedRequests: string[] = [];

    // Mock GET /api/products
    await page.route('*/**/api/products/**', async route => {
      interceptedRequests.push('/api/products');
      if (route.request().method() === 'GET') {
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            items: [{ id: 1, name: 'Test Product', price: 99.99 }]
          })
        });
      }
    });

    // Mock POST /api/cart
    await page.route('*/**/api/cart/**', async route => {
      interceptedRequests.push('/api/cart');
      if (route.request().method() === 'POST') {
        await route.abort('blockedbyclient');
      }
    });

    // Mock GET /api/user
    await page.route('*/**/api/user/**', async route => {
      interceptedRequests.push('/api/user');
      if (route.request().method() === 'GET') {
        await route.fulfill({
          status: 200,
          body: JSON.stringify({ id: 1, email: 'user@test.com' })
        });
      }
    });

    await use(page);
    console.log('Intercepted requests:', interceptedRequests);
  },
});

export { expect } from '@playwright/test';
"""

# ============================================================================
# EXAMPLE 5: Impact Analysis Output
# ============================================================================

SAMPLE_IMPACT_ANALYSIS = {
    "affected_flows": [
        "user_browse_products",
        "user_add_to_cart",
        "user_checkout"
    ],
    "needs_new_tests": [
        "user_payment_processing"
    ],
    "needs_updates": [
        "user_browse_products",
        "user_add_to_cart"
    ],
    "changed_files": [
        "src/components/ProductCard.tsx",
        "src/pages/cart.tsx",
        "src/api/checkout.ts"
    ],
    "changed_routes": [
        "/cart",
        "/checkout"
    ],
    "changed_apis": [
        "/api/v1/products",
        "/api/v2/checkout",
        "/api/payment/process"
    ],
    "changed_selectors": {
        "removed": [
            "[data-testid='product-card']",
            "[data-testid='add-btn']",
            "[class='old-checkout-table']"
        ],
        "added": [
            "[data-testid='product-item']",
            "[data-testid='add-to-cart-btn']",
            "[class='checkout-steps']"
        ]
    },
    "reasoning": "Component refactor changed selectors. API versioning updated endpoints. New payment flow requires new tests."
}

# ============================================================================
# EXAMPLE 6: Test File Output Summary
# ============================================================================

OUTPUT_SUMMARY = """
Phase 2 Pipeline Execution Result
==================================

Repository: /tmp/e2e-ai-test
Base Commit: a1b2c3d
PR Commit: e4f5g6h

DIFF ANALYSIS
─────────────
Files Changed: 3
  - src/components/ProductCard.tsx (11 lines added, 8 removed)
  - src/pages/cart.tsx (5 lines added, 3 removed)
  - src/api/checkout.ts (8 lines added, 2 removed)

Changes Detected:
  ✓ Component modifications: ProductCard
  ✓ API endpoint changes: 3 endpoints versioned
  ✓ Selector changes: 8 data-testids modified
  ✓ Route changes: /cart, /checkout updated

IMPACT ANALYSIS (via Claude)
────────────────────────────
Affected Flows: 3
  1. user_browse_products
  2. user_add_to_cart
  3. user_checkout

Test Updates Needed: 2
  1. user_browse_products (selector changes)
  2. user_add_to_cart (API endpoint change)

New Tests Required: 1
  1. user_payment_processing (new flow)

Reasoning:
  "ProductCard component selectors changed, affecting browse and cart flows.
   API endpoints versioned (v1→v2). New payment processor requires new test."

TEST GENERATION
───────────────
Generated Files:
  ✓ tests/e2e/user_payment_processing.spec.ts (NEW)
  ✓ fixtures.ts (updated)

Updated Files:
  ✓ tests/e2e/user_browse_products.spec.ts
  ✓ tests/e2e/user_add_to_cart.spec.ts

Test Code Quality:
  ✓ Valid TypeScript syntax (all tests compile)
  ✓ Proper Playwright imports
  ✓ API mocking configured
  ✓ Data selectors updated
  ✓ Wait conditions included

GITHUB ACTION OUTPUT (Ready for CI)
───────────────────────────────────
Output File: impact-analysis.json
Generated: 3 test files ready
Failed: 0
Action Status: ✅ SUCCESS

Recommended Next Steps:
1. Review generated tests for accuracy
2. Run: npm test -- tests/e2e/**/*.spec.ts
3. Update PR with test results
4. Merge when all tests pass
"""

if __name__ == "__main__":
    print("=" * 80)
    print("PHASE 2 PIPELINE - SAMPLE OUTPUTS")
    print("=" * 80)
    
    print("\n[EXAMPLE 1] Generated Product Browse Test:")
    print("-" * 80)
    print(GENERATED_TEST_PRODUCT_BROWSE[:500] + "\n...")
    
    print("\n[EXAMPLE 2] Generated Auth Flow Test:")
    print("-" * 80)
    print(GENERATED_TEST_AUTH[:400] + "\n...")
    
    print("\n[EXAMPLE 3] Generated Checkout Test:")
    print("-" * 80)
    print(GENERATED_TEST_CHECKOUT[:500] + "\n...")
    
    print("\n[EXAMPLE 4] Impact Analysis Output:")
    print("-" * 80)
    import json
    print(json.dumps(SAMPLE_IMPACT_ANALYSIS, indent=2)[:600] + "\n...")
    
    print("\n[EXAMPLE 5] Pipeline Execution Summary:")
    print("-" * 80)
    print(OUTPUT_SUMMARY[:800] + "\n...")
    
    print("\n" + "=" * 80)
    print("✅ All examples ready for GitHub Action consumption")
    print("=" * 80)
